# Generated by Django 4.2 on 2023-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False, verbose_name='Корневая')),
                ('position', models.IntegerField(default=1, verbose_name='Порядок')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'default_related_name': 'pages', 'ordering': ['position'], 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
