# Generated by Django 4.2 on 2023-04-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Трэк')),
                ('status', models.CharField(choices=[('new', 'Добавлен'), ('eha', 'В пути'), ('tut', 'Ожидает'), ('vse', 'Выдан')], default='new', max_length=3, verbose_name='Статус')),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=256)),
                ('package_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
