# Generated by Django 4.2 on 2023-04-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Трек')),
                ('status_change_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Трек-номера',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('bg_color', models.CharField(max_length=7, verbose_name='Цвет фона')),
                ('txt_color', models.CharField(blank=True, max_length=7, verbose_name='Цвет текста')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Статусы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('package_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Трек-номера пользователей',
            },
        ),
        migrations.AddField(
            model_name='packages',
            name='status',
            field=models.ForeignKey(default='new', on_delete=django.db.models.deletion.SET_DEFAULT, to='packages.status', to_field='code'),
        ),
    ]
