# Generated by Django 4.2 on 2023-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='status_change_date_manual',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
