# Generated by Django 4.2 on 2023-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packages_status_change_date_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='status_change_date_manual',
            field=models.CharField(default=None, max_length=17),
        ),
    ]
