# Generated by Django 4.2 on 2023-04-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_packages_status_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('bg_color', models.CharField(max_length=7, verbose_name='Цвет фона')),
                ('txt_color', models.CharField(blank=True, max_length=7, verbose_name='Цвет текста')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Статусы',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='packages',
            name='status',
            field=models.ForeignKey(default='new', on_delete=django.db.models.deletion.SET_DEFAULT, to='packages.status', to_field='code'),
        ),
    ]
