# Generated by Django 4.2 on 2023-04-17 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('ALA', 'Алматы'), ('AST', 'Астана')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('cargo_code', models.CharField(max_length=15)),
                ('is_activated', models.BooleanField(default=False)),
                ('city', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cities')),
                ('user', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='cargouser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
