# Generated by Django 4.2 on 2023-04-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={},
        ),
        migrations.RenameField(
            model_name='cargouser',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='city',
        ),
        migrations.AddField(
            model_name='cities',
            name='city_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='city_short_name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cargouser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cities'),
        ),
        migrations.AlterField(
            model_name='cargouser',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
