# Generated by Django 4.2 on 2023-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargouser',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
