# Generated by Django 4.2 on 2023-04-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargouser',
            old_name='user',
            new_name='username',
        ),
    ]
