# Generated by Django 4.2 on 2023-04-12 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargouser',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cities'),
        ),
        migrations.AlterField(
            model_name='cargouser',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cargouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargouser', to=settings.AUTH_USER_MODEL),
        ),
    ]
