# Generated by Django 4.2 on 2023-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cargouser_city_alter_cargouser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargouser',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
