# Generated by Django 4.2 on 2023-04-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_cargouser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargouser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cities'),
        ),
    ]
