# Generated by Django 4.2 on 2023-04-13 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_cargouser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='cargouser',
            name='otp',
        ),
        migrations.AddField(
            model_name='cargouser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='cargouser',
            name='user',
            field=models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='cargouser', to=settings.AUTH_USER_MODEL),
        ),
    ]
