# Generated by Django 4.2 on 2023-04-16 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_cargouser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstorage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
