# Generated by Django 4.2 on 2023-04-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpstorage_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Города'},
        ),
    ]
