# Generated by Django 4.2 on 2023-04-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_cities_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstorage',
            name='uuid',
        ),
    ]
