# Generated by Django 4.2 on 2023-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_otpstorage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargouser',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
